### PR TITLE
Allow disabling of SSL redirection

### LINKED ISSUE #20: MISP - How Disable Redirect http to https
Is there a way to disable MISP http redirect to https? We disabled tcp/443 within docker-compose.yml and are not able to get MISP to respond to http tcp/80 requests.

We are using MISP in MIcrosoft Azure with an Application Gateway that will be performing SSL Offloading and do not require https redirection on the backend, but... we are receiving Gateway 504 errors, i.e., backend timeouts... and we suspect it is related to what appears to be a "baked in" MISP http redirect to https that we would like to disable.

We see a MISP and MISP80 configuration within the misp-misp-core-1, but are not sure this is related to our request.

Any suggestions to remediate are greatly appreciated.

---

https://www.circl.lu/doc/misp/administration/#how-to-redirect-http-to-https

https://github.com/MISP/MISP/issues/4405 (user claims they were able to disable https redirect and self-signed certificate, but does not include details on how)

https://githubhelp.com/harvard-itsecurity/docker-misp/issues/47
https://web.archive.org/web/20200910000555/https://github.com/harvard-itsecurity/docker-misp/issues/47

https://eugit.opencloud.lu/MISP/misp-docker/commit/c57f2669ec8f34a934fc089b2c263f607dc4bbc6#diff-35b8c13cf2eb2a194eada000eb310d65aed53b2a
- this link hints towards an option within a MISP-Docker YML configuration that predates this project
- "NOREDIR=true" #Do not redirect port 80

### PR DESCRIPTION
**Pull request by ostefano**

### CODE REVIEW

**Comment by gritty-Kitty** [comment]
Apologies for delay, and thank you in advance for your efforts. Updated docker-compose.yml with your changes, but trying to determine how to pull the noredirect build. Can you provide a hint on the convention of how to specify a specific build within the Docker-Compose.yml?

I have tried various sub-tags, and tried fudging the image location, but gave up after about an hour.

misp-core:
    image: ghcr.io/misp/misp-docker/misp-core:latest

**Comment by kelke** [comment]
This is exactly what I needed. Hope this will get merged soon 👍🏼

**Comment by ostefano** [comment]
@gritty-Kitty , you need to build the image first, then just use the tag `latest`. Obviously you can test it only where you build it.

@kelke only after there is some testing, so any help is appreciated in that direction :)

**Comment by gritty-Kitty** [comment]
Good afternoon,

I have attempted a build, but have stalled. Any insight on how to resolve is greatly appreciated.

Had to edit Dockerfile CORE_TAG=2.4 so it would resolve and compile.
https://raw.githubusercontent.com/MISP/MISP/2.4/app/composer.json
... but, then it appeared to choke at the end.

<see attached>

---


infinity@ONHMISP0ZWF001:~/misp-docker-noredirect/core$ sudo docker image prune
infinity@ONHMISP0ZWF001:~/misp-docker-noredirect/core$ sudo docker image ls
REPOSITORY                              TAG       IMAGE ID       CREATED         SIZE
ghcr.io/misp/misp-docker/misp-modules   latest    d651cccc2691   4 days ago      1.15GB
ghcr.io/misp/misp-docker/misp-core      latest    13645676ebeb   4 days ago      985MB
mariadb                                 10.11     161aacd369c1   11 days ago     404MB
redis                                   7.2       d1397258b209   7 weeks ago     138MB
portainer/portainer-ce                  latest    1a0fb356ea35   2 months ago    294MB
ixdotai/smtp                            latest    6fc2f5b2c12a   4 months ago    93.6MB
hello-world                             latest    d2c94e258dcb   10 months ago   13.3kB

infinity@ONHMISP0ZWF001:~/misp-docker-noredirect/core$ sudo docker build -t misp-core .
https://raw.githubusercontent.com/MISP/MISP//app/composer.json -does not exist

**Comment by ostefano** [comment]
You need to create the `.env` file as per README before building the image.

**Comment by gritty-Kitty** [comment]
Good morning,

Our implementation is based on Ubuntu 22.04 LTS, Docker, and Portainer.

I appear to lack the knowledge and experience required to compile and test. I struggled with Docker at the command line with a .env file that did not appear to be recognized (same output as above).

https://stackoverflow.com/questions/47968875/how-to-build-docker-with-env-file

Then turned my focus towards building an Image in Portainer, but it also exhibited errors during the build process. There does not appear to be any mechanism that allows me to bind a .env file to the Portainer Image creation process.

**Comment by ostefano** [comment]
The error you are seeing is because of an old version of docker (or docker-compose).

**Comment by gritty-Kitty** [comment]
Good afternoon,

The server is a new build (~2-weeks old) using Microsoft Azure Marketplace Ubuntu 22.04 LTS with all updates/upgrades applied weekly. The sole purpose of this server is to host MISP, but due to aging dependencies, we were forced to entertain a Docker-instance, and found your project. Docker was pulled using apt-get, and Portainer was pulled from Docker when installed. Posted here for your awareness.

sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose
sudo docker volume create portainer_data
sudo docker run -d -p 18000:8000 -p 9443:9443 -p 19000:9000 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
sudo docker ps


Can't comment on age or freshness of Docker or Docker-Compose, other than this was a fresh installation.

My build efforts revolved around the DockerFile and creating a new Image so I could return to my Portainer Stack and attempt a redeployment, but could never get the build to work.



Apologies in advance. I tried.

**Comment by ostefano** [comment]
I've just merged it.

**Comment by kelke** [comment]
I did not find any bugs as well. Works just as expected

**Pull request merged**
