### PR TITLE
Fix redis password leakage in entrypoint_fpm.sh

### PR DESCRIPTION
**Pull request by wmax641**
entrypoint_fpm.sh prints out Redis password in plaintext to stdout
Issue #138

### CODE REVIEW

**Comment by wmax641** [comment]
Before:
```bash
~ REDIS_HOST="redis.asdf.local"
~ REDIS_PASSWORD="hello123!"

~ echo "Configure PHP | Setting 'session.save_path = '$(echo $REDIS_HOST | grep -E '^\w+://' || echo tcp://$REDIS_HOST):6379?auth=${REDIS_PASSWORD}'"
Configure PHP | Setting 'session.save_path = 'tcp://redis.asdf.local:6379?auth=hello123!'
```

After:
```bash
~ echo "Configure PHP | Setting 'session.save_path = '$(echo $REDIS_HOST | grep -E '^\w+://' || echo tcp://$REDIS_HOST):6379?auth=${REDIS_PASSWORD//?/x}'"
Configure PHP | Setting 'session.save_path = 'tcp://redis.asdf.local:6379?auth=xxxxxxxxx'
```

**Comment by ostefano** [comment]
As you noticed in https://github.com/MISP/misp-docker/issues/134 making sure that redis password is correctly set is quite important, and most issues users encounter are due to credentials/password not propagating correctly.

I am not planning to merge this at this stage, unless you make this configurable (via an env var) and you cover also all other cases where the leakage takes place.

**Review by ostefano — CHANGES_REQUESTED** [review]
See my last comment

**Comment by ostefano** [comment]
Will close this due to lack of interest

**Pull request closed without merging**
